input Action {
  # Url
  navigate: String
  # Number in Seconds
  sleep: Int
  # CSS Selector
  waitVisible: String
  # Fill a form element
  sendKeys: Input
  # CSS Selector
  click: String
  # JS Code
  evalJS: String
  # Collect a Runtime variable
  runtimeVar: Selector
}