input Input {
  cssSelector: String!
  value: String!
}

input Selector {
  HTMLAttribute: String
  innerHTML: Boolean
  regex: String
  subSelectors: [Selector]
  cssSelector: String
  key: String!
  type: SelectorType!
}

enum SelectorType {
  object_array
  string_array
  object_prop
  string_prop
}