input Input {
  cssSelector: String!
  value: String!
}

input Selector {
  HTMLAttribute: String
  innerHTML: Boolean
  regex: String
  subSelectors: [Selector]
  key: String
  flat: Boolean
  cssSelector: String!
}