input Action {
  navigate: String
  sleep: Int
  waitVisible: String
  sendKeys: Input
  click: String 
  evalJS: String
  store: Selector
}

# helper types
input Input {
  selector: String!
  value: String!
}

input Selector {
  attribute: String
  element: String!
}