input Action {
  navigate: String
  sleep: Int
  waitVisible: String
  sendKeys: Input
  click: String 
  evalJS: String
  runtimeVar: Selector
}

# helper types
input Input {
  selector: String!
  value: String!
}

input Selector {
  attribute: String
  element: String!
}

input OutputMap {
  attribute: String
  element: String!
  key: String!
  groupElement: String
  groupKey: String
}