scalar Map

type Output {
  runtimeVars: [RuntimeVar]
  output: Map!
}

input OutputCollectionMap {
  # Name of collection
  name: String!
  # Name of key in result JSON
  # If not set the collection name will be choosen for this
  key: String
  hideDefaultValueKeys: Boolean
  selectors: [Selector]!
}

type RuntimeVar {
  name: String!
  attribute: String
  element: String!
  value: String
}