type Output {
  runtimeVars: [RuntimeVar]
  output: [OutputCollection]
}

input OutputCollections {
  name: String!

  attribute: String
  element: String!
  key: String!
  groupElement: String
  groupKey: String
}

type OutputCollection {
  name: String!

  key: String!
  element: String!
  index: Int!
  value: String!
  groupElement: String!
  groupIndex: Int!
  groupKey: String!
}

type RuntimeVar {
  name: String!
  attribute: String
  element: String!
  value: String
}