type Output {
  runtimeVars: [RuntimeVar]
  output: [OutputElement]
}

type OutputElement {
  key: String!
  selector: String!
  index: Int!
  value: String!
}

type RuntimeVar {
  name: String!
  attribute: String
  element: String!
  value: String
}